### ISSUE TITLE
nickelpro ToDo List

### ISSUE THREAD

**Issue by nickelpro** [PrismarineJS/mineflayer#2097]
I don't know where to put this, but this is a list of things to do after 1.17. If I could get triage perms that would be :man_cook: :kiss: 

- [ ] All inventory/crafting/enchanting/etc plugins hard code their target slots, they shouldn't do that
- [ ] Tons of es6 port cruft, using `let [variable]` at the top of functions, etc
- [ ] Crafting tests don't verify items were actually crafted
- [ ] Example-based tests aren't debuggable, replace them with purpose-built tests
- [ ] Explore race conditions in creative inventory interactions
- [ ] Assess refactoring out callbackify for proper async APIs
- [ ] **Error handling for scuffed packet encoding**
- [ ] Proper handling for rejected clicks, window rollback code?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/issues/1482 about callbackify
Plan is to check that nobody use callbacks anymore, then remove callbacks

Would be great to do it (but indeed after 1.17 is done please)
